version: '3.8'

services:
  mysqldb:
    build: 
      context: .
      dockerfile: dockerfiles/mysql.dockerfile
    ports:
      - '3306:3306'
    env_file:
      - ./env/mysql.env
    # volumes:
    #   - ./data-mysql/mysql:/var/lib/mysql
  api:
    build: 
      context: .
      dockerfile: dockerfiles/api.dockerfile
    ports:
      - '80:8000'
    volumes:
      - ./ChatBot:/api
    depends_on:
      - mysqldb